// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#ifndef PRACTICA_V2_H
#define PRACTICA_V2_H

#include <ngrest/common/Service.h>
#include <string>
#include "ListaUsuarios.h"
#include "ColaServicios.h"
#include "PilaRecursos.h"

//! Dummy description for the service
/*! Some detailed description of the service */
// '*location' comment sets resource path for this service
// *location: practica_v2
class practica_v2: public ngrest::Service
{
public:
      // *method: GET
    std::string echo(const std::string& text);

    // *method: POST
    // *location: /newuser
    std::string newuser(const Usuario& user);

    // *method: POST
    // *location: /newservice
    std::string newservice(const Servicio& serv);

    // *method: POST
    // *location: /newrecurso
    std::string newrecurso(const Recurso& rec);

    // *method: GET
    // *location: /getusuarios
    std::list<Usuario> getusuarios();

    // *method: GET
    // *location: /getservicios
    std::list<Servicio> getservicios();

    // *method: GET
    // *location: /getrecursos
    std::list<Recurso> getrecursos();

    // *method: GET
    std::string getrecurso(const std::string& id_usuario);
};


#endif // PRACTICA_V2_H
