// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#include "practica_v2.h"

std::string practica_v2::echo(const std::string& text)
{
    return "Hi, " + text;
}

ListaUsuarios lUsers;
ColaServicios cServices;
PilaRecursos pRecursos;

std::string practica_v2::newuser(const Usuario& user){
  std::string r;

  lUsers.insertarOrdenado(user);

  r = "usuario creado correctamente";

  return r;

}

std::string practica_v2::newservice(const Servicio& serv){
  std::string r;

  cServices.insertarAlFinal(serv);

  r = "servicio creado correctamente";

  return r;

}

std::string practica_v2::newrecurso(const Recurso& rec){
  std::string r;

  pRecursos.insertarAlInicio(rec);

  r = "servicio creado correctamente";

  return r;
}

std::list<Usuario> practica_v2::getusuarios(){
  std::list<Usuario> usuarios = lUsers.getList();
  return usuarios;
}

std::list<Servicio> practica_v2::getservicios(){
  std::list<Servicio> servicios = cServices.getList();
  return servicios;
}

std::list<Recurso> practica_v2::getrecursos(){
  std::list<Recurso> recursos = pRecursos.getList();
  return recursos;
}

std::string practica_v2::getrecurso(const std::string& id_usuario){
  std::string userinfo = lUsers.getUserName(id_usuario);
  std::string servicio = cServices.getServiceByID(id_usuario);
  std::string recurso = pRecursos.pop();

  return "id_session: "+ servicio + " , usuario: "+ userinfo + " , " +recurso;
}
